### ISSUE TITLE
removeLayer（）删除图层导致cesium崩溃

### ISSUE THREAD

**Issue by Tysep** [marsgis/mars3d#1]
代码如下：
```` 
const removeLayerById = ID => {
    if (map.getLayerById(ID)) {
      map.removeLayer(map.getLayerById(ID))
    }
} 
````
不知道是不是我的使用方式有问题  

报错如下：
![image](https://user-images.githubusercontent.com/51128070/114006645-33b44a00-9893-11eb-8a03-271c9a4ee0ca.png)

**Comment by muyao1987** [comment]
写法没有问题，可以使用最新版本试下。
