### ISSUE TITLE
向 GraphicLayer 添加 PolygonPrimitive 对象时报错

### ISSUE THREAD

**Issue by cjh804263197** [marsgis/mars3d#10]
### 描述
在向 GraphicLayer 添加 PolygonPrimitive 对象时报错，错误如下图：
![image](https://user-images.githubusercontent.com/15188182/148678114-12c3a500-5ad2-46e0-84eb-826420407592.png)

示例代码：
```javascript
const positions = [
  new Cartesian3(-2877753.8912436897, 4848831.729657154, 2971314.4878532737),
  new Cartesian3(-2877782.6632767506, 4848822.004413433, 2971302.1542773163),
  new Cartesian3(-2877798.206913736, 4848827.3474626485, 2971278.564903176),
]
const polygonPrimitive = new mars3d.graphic.PolygonPrimitive({
	positions,
	style: {
		color: '#d40000',
		opacity: 0.4,
		outline: true,
		outlineColor: '#d40000',
		outlineOpacity: 1,
		clampToGround: true
	}
})

// graphicLayer 的创建过程省略
graphicLayer.addGraphic(polygonPrimitive)
```

### 版本信息
mars3d: v3.1.20
mars3d-cesium: 1.89.0

**Comment by muyao1987** [comment]
当前版本可以加属性：outlineWidth: 2, 解决报错问题。 这个错误将在3.1.22修复。

  const polygonPrimitive = new mars3d.graphic.PolygonPrimitive({
    positions,
    style: {
      color: "#d40000",
      opacity: 0.4,
      outline: true,
      outlineWidth: 2,
      outlineColor: "#d40000",
      outlineOpacity: 1,
      clampToGround: true,
    },
  });
