### ISSUE TITLE
基于3dtiles做剖面分析出错

### ISSUE THREAD

**Issue by jbbill** [marsgis/mars3d#12]
![1645178386(1)](https://user-images.githubusercontent.com/52019655/154661031-e6486ca6-15e9-4ac7-88d1-a08055eadda9.png)
![1645178448(1)](https://user-images.githubusercontent.com/52019655/154661033-342fc949-31b1-487c-8029-3d34359a4a45.png)

**Comment by muyao1987** [comment]
更新到最新版本后测试下呢？或者描述下复现步骤。
