### ISSUE TITLE
没距离选择点的时候，容易飘，很难选，很多时候明明是不天10米的距离，却测量显示是100多米，换了角度查看，原来测量点选到了高空中，

### ISSUE THREAD

**Issue by EulerWong** [marsgis/mars3d#19]
没距离选择点的时候，容易飘，很难选，很多时候明明是不天10米的距离，却测量显示是100多米，换了角度查看，原来测量点选到了高空中，可是空中明明没有任何东西。

我感觉这个是个BUG，选中的点根本不是我在图上点的的那个点。

**Comment by muyao1987** [comment]
是否可以提供测试代码或截图 ，可以加微信沟通，http://mars3d.cn/community.html

**Comment by EulerWong** [comment]
距离选择点的时候，容易飘，很难选，很多时候明明是不到10米的距离，却测量显示是100多米，换了角度查看，原来测量点选到了高空中，可是空中明明没有任何东西。

我感觉这个是个BUG，选中的点根本不是我在图上点的的那个点。

根据我的推测，可能是卫星地形与倾斜摄影的地形不能100%重合导致，可是即便我在代码里怎么设置 position: { alt: xxx }, 都不可能是真实的与实际的完全吻合的。所以我觉得这个选点或测量的功能有待修改。

这个的代码很简单，如下图。

 
<img width="501" alt="无标题" src="https://user-images.githubusercontent.com/6688986/207241446-6e9a4608-14be-40e2-8e32-02986f1e32fa.png">

**Comment by muyao1987** [comment]
使用v3.4.18测试看看
