### ISSUE TITLE
遮罩图层仅支持一个吗？

### ISSUE THREAD

**Issue by ShareQiu1994** [marsgis/mars3d#2]
经过测试，遮罩层只能是在数据为单独一个面的情况下使用，如果在数据为多个面的情况(使用场景:某些行政区包括多个面)下，加载遮罩的geojson会导致程序无法正常显示，大佬是否有进一步优化此功能？

**Comment by muyao1987** [comment]
之前是只支持1个面，感谢您的反馈，我们已优化加上对多个面的情况的支持，将在下一个版本v3.1.1发布。

**Comment by muyao1987** [comment]
如果您希望我们及时处理您的问题，也可以加我们微信群交流和反馈  [http://mars3d.cn/contact](http://mars3d.cn/contact)
