### ISSUE TITLE
百度离线地图加载偏移问题

### ISSUE THREAD

**Issue by ideazoom** [marsgis/mars3d#20]
由于百度离线地图的切片规则和高德不同，所以加载百度离线地图位置不对。请问有何解决办法？
config.json配置
{
        "pid": 10,
        "name": "百度电子",
        "icon": "http://localhost:9990/static/images/basemaps/bd_vec.png",
        "type": "xyz",
        "url": "http://localhost:9990/maps/baidu/vec/{z}/{x}/{y}.png",        
        "chinaCRS": "BAIDU",
        "minimumLevel": 3,
        "maximumLevel": 19        
      }

**Comment by muyao1987** [comment]
参考示例：http://mars3d.cn/editor-vue.html?id=layer-tile/online/baidu
```
{
"pid": 10,
"name": "百度电子",
"icon": "http://localhost:9990/static/images/basemaps/bd_vec.png",
"type": "baidu",
"url": "[http://localhost:9990/maps/baidu/vec/{z}/{x}/{y}.png](http://localhost:9990/maps/baidu/vec/%7Bz%7D/%7Bx%7D/%7By%7D.png)",
"minimumLevel": 3,
"maximumLevel": 19
}
```

**Comment by ideazoom** [comment]
> 参考示例：http://mars3d.cn/editor-vue.html?id=layer-tile/online/baidu
> 
> ```
> {
> "pid": 10,
> "name": "百度电子",
> "icon": "http://localhost:9990/static/images/basemaps/bd_vec.png",
> "type": "baidu",
> "url": "http://localhost:9990/maps/baidu/vec/{z}/{x}/{y}.png",
> "minimumLevel": 3,
> "maximumLevel": 19
> }
> ```


修正如下：
{
        "pid": 10,
        "name": "百度电子",
        "icon": "http://localhost:9990/static/images/basemaps/bd_vec.png",
        "type": "baidu",
        "url": "http://localhost:9990/maps/baidu/vec/NanJing/{z}/{x}/{y}.png"
      }

还是加载不出来。 
离线地图是用水经注软件下载并按官方文档导出的瓦片数据

Mars3D 
版 本 号：3.1.11    Cesium版本：1.84
编译日期：2021-11-07 14:54:49

虽然版本有些老，希望在不升级的情况下能解决此问题。
