### ISSUE TITLE
卫星轨迹 closure 2d 不生效。

### ISSUE THREAD

**Issue by yangxyo** [marsgis/mars3d#24]
closure 参数，闭合轨道圆在2d及2.5d模式中不生效。
包版本为 3.5.6

**Comment by muyao1987** [comment]
人造地球卫星和地心连线与地面的交点称作星下点。人造地球卫星运动和地球自转使星下点在地球表面移动所形成的轨迹就是星下点轨迹。将星下点轨迹画在地图上，便是星下点轨迹图，也就是二维模式下展示的线。如果在星下点轨迹图上再注明所对应的时间，就可以看出某一时刻卫星在何地上空。

在不同的轨道上运行的卫星，星下点轨迹也不同。

大部分卫星是一种近地卫星在麦卡托投影地图上的星下点轨迹图，一般是多圈星下点轨迹的曲线族；
地球同步轨道卫星的星下点轨迹是条首尾相接的封闭曲线；
地球静止轨道卫星的星下点轨迹为赤道上的一个点。
轨道的星下点轨迹所能到达的最南和最北点的地心纬度，数值上等于轨道倾角。
