### ISSUE TITLE
建议控制台不要默认输出

### ISSUE THREAD

**Issue by enpitsuLin** [marsgis/mars3d#25]
应该提供用户开关的选项或者提供自定义输出信息的能力，使用`console.log`输出变量不会被GC有可能会导致内存泄漏，3d场景下还是蛮重要的

**Comment by muyao1987** [comment]
可以执行代码关闭打印   mars3d.Log.hasInfo(false)

http://mars3d.cn/api/Log.html?classFilter=log#.hasInfo

**Comment by enpitsuLin** [comment]
@muyao1987 学习了，谢谢答复

**Comment by liseri** [comment]
@muyao1987  请问， 为什么mars3d.Log.hasWarn(false)不起作用， warn仍然能输出
