### ISSUE TITLE
在3.6.0版本重写TerrainClip后占用GPU太高

### ISSUE THREAD

**Issue by journeagle** [marsgis/mars3d#27]
mars3d.thing.TerrainClip在版本3.6.0重写后，占用GPU太高，操作明显卡顿，希望能优化下该功能
![image](https://github.com/marsgis/mars3d/assets/17492155/8f9c6cb0-f189-4b4e-8eee-eda80ecdc8a0)
![screenshot](https://github.com/marsgis/mars3d/assets/17492155/0cc20e54-bb01-4f39-8860-11c05a5c8d2a)

link : http://mars3d.cn/editor-vue.html?id=graphic/apply/quyuNum

**Comment by muyao1987** [comment]
已优化，下个版本发布生效，可以先在线体验 http://mars3d.cn/editor-vue.html?id=graphic/apply/quyuNum
