### ISSUE TITLE
mars3d3.6.15版本 mars3d-cesium1.112版本开发环境下全局使用Cesium报错

### ISSUE THREAD

**Issue by m1655280161** [marsgis/mars3d#28]
1.问题描述：
- mars3d@3.6.15版本 mars3d-cesium@1.112下开发环境下全局使用Cesium报错，生产环境OK。
- mars3d@3.4.26版本开发环境全局使用Cesium报错不报错.
2.复现步骤：
新建一个vite+vue项目，
main.js中引入：

// 引入cesium基础库
import "mars3d-cesium/Build/Cesium/Widgets/widgets.css"
import * as Cesium from "mars3d-cesium"
// 导入mars3d主库
import "mars3d/dist/mars3d.css"
import * as mars3d from "mars3d"

在HelloWorld.vue文件中console.log(Cesium)报错：Cesium is not defined.
![image](https://github.com/marsgis/mars3d/assets/40781133/ca087139-249d-421d-8051-d3279990f87a)

**Comment by muyao1987** [comment]
正常在代码这样用就行

import * as mars3d from "mars3d";
let Cesium = mars3d.Cesium
 

console.log(Cesium) 


如果想挂载window，就手动挂载下，window.Cesium = Cesium
