### ISSUE TITLE
如图，utils中是否能提供国内坐标的纠偏方法

### ISSUE THREAD

**Issue by Eva-Skye** [marsgis/mars3d#30]
![1cd220fa69b0640715562ba85e6df48](https://github.com/marsgis/mars3d/assets/45868259/181c2bd2-e9eb-4a50-bae1-4bb5d59b9ed7)

**Comment by muyao1987** [comment]
先纠偏  http://mars3d.cn/api/PointTrans.html?classFilter=pointt

再转为2000  http://mars3d.cn/api/PointTrans.html?classFilter=pointt#.proj4Trans
