### ISSUE TITLE
如图，请问在配置参数中设置纠偏坐标系和在geojsonlayer中设置纠偏坐标系有什么不同

### ISSUE THREAD

**Issue by Eva-Skye** [marsgis/mars3d#31]
![ae2c77b7f07fdceac2917f4821dd220](https://github.com/marsgis/mars3d/assets/45868259/0bb7a1e4-d63f-4679-b26f-8303a82fbc83)
基础场景中只加载了火星坐标下的矢量，在mapoptions map3d层级下设置总体纠偏参数和在layer中单独设置纠偏参数，geojsonlayer的位置不一样，想问问这两个参数有什么区别呢

**Comment by Eva-Skye** [comment]
在geojsonlayer中设置纠偏效果良好，但是在map3d下设置，这个参数仿佛失效了

**Comment by muyao1987** [comment]
1. map.chinaCRS：GCJ02 会使整个地图场景基础变为GCJ02坐标系，叠加GCJ02数据就无须纠偏了，但在地图上获取的坐标也是GCJ02坐标。

2. 如果不改变map，只在图层加chinaCRS：GCJ02，操作的是将图层数据进行了纠偏，叠加到了WGS84坐标系的map上，在地图上获取的坐标也是WGS84无偏坐标。
