### ISSUE TITLE
GeoJsonLayer图层透明度设置问题

### ISSUE THREAD

**Issue by giser1119** [marsgis/mars3d#33]
### 当在geojsonlayer构造参数symbol设置透明度后，重新设置图层透明度好像有透明度叠加效果
`  graphicLayer = new mars3d.layer.GeoJsonLayer({
    name: "全国省界",
    url: "//data.mars3d.cn/file/geojson/areas/100000_full.json",
    format: simplifyGeoJSON, // 用于自定义处理geojson
    symbol: {
      type: "polyline",
      styleOptions: {
        opacity:0.3,
        width: 2,
        color:"#f00"
      }
    },
    flyTo: true
  })`
`graphicLayer.opacity = 1`

![1](https://github.com/marsgis/mars3d/assets/52056728/49165028-30d8-46b3-aa26-212bdd0a1dc3)

**Comment by muyao1987** [comment]
graphicLayer.opacity = 1 不改变内部透明度，如果需要改变symbol.styleOptions请调用 graphicLayer.setOptions更新即可。
