### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by guchengjie** [marsgis/mars3d#7]
react项目webpack配置，运行时包这个错误
Uncaught TypeError: Super expression must either be null or a function
    at _0x49bb40.<computed> (mars3d.js:25)
    at mars3d.js:30
    at Module.<anonymous> (mars3d.js:30)
    at _0x1a2b01 (mars3d.js:25)

**Comment by entenity** [comment]
不开源 问题还多 类型声明 一堆问题
declare class HeatLayer extends BaseLayer {
  constructor(options: {
    id?: string | number
    pid?: string | number
    name?: string
    show?: boolean
    center?: any
    positions?: LatLngPoint[] | any[][] | String[] | Cesium.Cartesian3[]
    heatStyle?: {
      maxOpacity?: number
      minOpacity?: number
      blur?: number
      radius?: number
      gradient?: any
    }
    style?: {
      父类?: RectanglePrimitive.StyleOptions
      opacity?: boolean
      arc?: boolean
      arcRadiusScale?: boolean
      arcBlurScale?: boolean
    }
    maxCanvasSize?: number
    minCanvasSize?: number
    delayTime?: number
  })
