### ISSUE TITLE
引用 mars3d-cesium 时，提示：找不到类型定义模块

### ISSUE THREAD

**Issue by cjh804263197** [marsgis/mars3d#8]
### 问题
在代码中试图引入 mars3d-cesium 时，ts会报错，找不到类型定义模块
![image](https://user-images.githubusercontent.com/15188182/147634773-3baf3a4b-29e8-4cdd-9248-1cbc1661c91a.png)

### 原因
在 `node_modules/mars3d-cesium/Build/Cesium/Cesium.d.ts` 中定义的模块是
```ts
declare module "cesium" {
    ...
}
```
期望其改为
```ts
declare module "mars3d-cesium" {
    ...
}
```

**Comment by muyao1987** [comment]
升级到 "mars3d-cesium": "^1.88.1",
