### ISSUE TITLE
加载3DTiles三维模型时setCursor设置会被覆盖

### ISSUE THREAD

**Issue by yucheng1207** [marsgis/mars3d#9]
加载3DTiles三维模型并使用[setCursor](http://mars3d.cn/api/Map.html?classFilter=map#setCursor)设置鼠标状态后 移动模型鼠标状态会变回default

**Comment by muyao1987** [comment]
收到，目前版本需要监听编辑完成事件后，手动setCursor下。下个版本会修复

**Comment by muyao1987** [comment]
v3.1.21 已经修复这个问题
